# Generated by Django 2.1.2 on 2018-11-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cards',
            field=models.ManyToManyField(to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=200),
        ),
    ]
