# Generated by Django 2.1.2 on 2018-11-10 18:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_Profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
