version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1080:80