# Generated by Django 2.1.3 on 2018-11-20 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_source', models.IntegerField()),
                ('credits_target', models.IntegerField()),
                ('cards_source', models.ManyToManyField(related_name='cards_source', to='cards.Card')),
                ('cards_target', models.ManyToManyField(related_name='cards_target', to='cards.Card')),
                ('user_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_source', to=settings.AUTH_USER_MODEL)),
                ('user_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_targer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
