# Generated by Django 2.1.3 on 2018-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
